// Generated by tools/gen_nvg_compat.py from MIG_Helmets.pbo - re-run the tool, do not edit.
#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = "RONIM - NVG overlay compat (MIG_Helmets)";
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"azeroot_ronim_main", "FPANO", "GPNVG18", "PVS14", "PVS31", "Visor"};
        skipWhenMissingDependencies = 1;
        author = "Root, Azer0";
        authors[] = {"Root", "Azer0"};
        url = "https://github.com/A3-Root/Azer0ot_RONIM";
        VERSION_CONFIG;
    };
};

// modelOptics blanked so the engine no longer draws the overlay; RONIM draws the same texture itself
class CfgWeapons {
    class NVGoggles;
    class MIG_FPANO_BLK: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\FPANO\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\fpano\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_FPANO_DayOps_BLK: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\FPANO\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\fpano\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_FPANO_DayOps_FDE: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\FPANO\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\fpano\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_FPANO_FDE: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\FPANO\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\fpano\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_Galvion_Visor_DOWN: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\Galvion\Visor\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\galvion\visor\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.034985, 0.001204, -0.000001};
    };
    class MIG_Galvion_Visor_UP: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\Galvion\Visor\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\galvion\visor\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.034985, 0.001204, -0.000001};
    };
    class MIG_GPNVG18_BLK: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\GPNVG18\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\gpnvg18\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_GPNVG18_DayOps_BLK: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\GPNVG18\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\gpnvg18\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_GPNVG18_DayOps_FDE: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\GPNVG18\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\gpnvg18\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_GPNVG18_FDE: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\GPNVG18\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\gpnvg18\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_PVS14_B: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS14\optic\pvs_optic_B.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs14\optic\pvs_optic_b_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.042302, 0.041198, 0.001204, -0.000001};
    };
    class MIG_PVS14_B_TAN: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS14\optic\pvs_optic_B.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs14\optic\pvs_optic_b_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.042302, 0.041198, 0.001204, -0.000001};
    };
    class MIG_PVS14_DayOps_B: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS14\optic\pvs_optic_B.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs14\optic\pvs_optic_b_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.042302, 0.041198, 0.001204, -0.000001};
    };
    class MIG_PVS14_DayOps_B_TAN: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS14\optic\pvs_optic_B.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs14\optic\pvs_optic_b_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.042302, 0.041198, 0.001204, -0.000001};
    };
    class MIG_PVS14_DayOps_L: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS14\optic\pvs_optic_L.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs14\optic\pvs_optic_l_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.037602, 0.03662, 0.001204, -0.000001};
    };
    class MIG_PVS14_DayOps_R: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS14\optic\pvs_optic_R.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs14\optic\pvs_optic_r_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.037602, 0.03662, 0.001204, -0.000001};
    };
    class MIG_PVS14_L: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS14\optic\pvs_optic_L.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs14\optic\pvs_optic_l_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.037602, 0.03662, 0.001204, -0.000001};
    };
    class MIG_PVS14_R: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS14\optic\pvs_optic_R.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs14\optic\pvs_optic_r_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.037602, 0.03662, 0.001204, -0.000001};
    };
    class MIG_PVS31_DayOps_STD: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS31\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs31\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_PVS31_LOW: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS31\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs31\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_PVS31_LOW_Up: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS31\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs31\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
    class MIG_PVS31_STD: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "MIG\MIG_Helmets\PVS31\optic\pvs_optic.p3d";
        azeroot_ronim_maskTexture = "\mig\mig_helmets\pvs31\optic\pvs_optic_ca2.paa";
        azeroot_ronim_opticQuad[] = {0.047002, 0.045775, 0.001204, -0.000001};
    };
};
