// Generated by tools/gen_nvg_compat.py from rhs_c_troops.pbo - re-run the tool, do not edit.
#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = "RONIM - NVG overlay compat (rhs_c_troops)";
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"azeroot_ronim_main", "rhs_c_troops"};
        skipWhenMissingDependencies = 1;
        author = "Root, Azer0";
        authors[] = {"Root", "Azer0"};
        url = "https://github.com/A3-Root/Azer0ot_RONIM";
        VERSION_CONFIG;
    };
};

// modelOptics blanked so the engine no longer draws the overlay; RONIM draws the same texture itself
class CfgWeapons {
    class NVGoggles;
    class rhs_1PN138: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\rhsafrf\addons\rhs_infantry2\gear\nvg\mono_opt";
        azeroot_ronim_maskTexture = "\rhsafrf\addons\rhs_infantry2\gear\nvg\data\mono_reticle.paa";
        azeroot_ronim_opticQuad[] = {0.336568, 0.336568, -0.000006, 0.00003};
    };
    class rhs_6m2_nvg: rhs_1PN138 {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\Weapons_F\empty";
    };
};
