// Generated by tools/gen_nvg_compat.py from ace_nightvision.pbo - re-run the tool, do not edit.
#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = "RONIM - NVG overlay compat (ace_nightvision)";
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"azeroot_ronim_main", "ace_nightvision"};
        skipWhenMissingDependencies = 1;
        author = "Root, Azer0";
        authors[] = {"Root", "Azer0"};
        url = "https://github.com/A3-Root/Azer0ot_RONIM";
        VERSION_CONFIG;
    };
};

// modelOptics blanked so the engine no longer draws the overlay; RONIM draws the same texture itself
class CfgWeapons {
    class NVGoggles;
    class NVGoggles_INDEP;
    class NVGoggles_OPFOR;
    class ACE_NVG_Wide: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\z\ace\addons\nightvision\models\ACE_nvg_wide_optics";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.056176, 0.031833, -0.000061, -0.000052};
    };
    class ACE_NVG_Wide_Black: NVGoggles_OPFOR {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\z\ace\addons\nightvision\models\ACE_nvg_wide_optics";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.056176, 0.031833, -0.000061, -0.000052};
    };
    class ACE_NVG_Wide_Green: NVGoggles_INDEP {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\z\ace\addons\nightvision\models\ACE_nvg_wide_optics";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.056176, 0.031833, -0.000061, -0.000052};
    };
    class NVGogglesB_grn_F: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\weapons_f_exp\reticle\ENVG.p3d";
    };
    class NVGogglesB_gry_F: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\weapons_f_exp\reticle\ENVG.p3d";
    };
};
