// Generated by tools/gen_nvg_compat.py from weapons_f.pbo - re-run the tool, do not edit.
#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = "RONIM - NVG overlay compat (weapons_f)";
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"azeroot_ronim_main", "A3_Weapons_F"};
        skipWhenMissingDependencies = 1;
        author = "Root, Azer0";
        authors[] = {"Root", "Azer0"};
        url = "https://github.com/A3-Root/Azer0ot_RONIM";
        VERSION_CONFIG;
    };
};

// modelOptics blanked so the engine no longer draws the overlay; RONIM draws the same texture itself
class CfgWeapons {
    class Binocular;
    class NVGoggles: Binocular {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\weapons_f\reticle\optics_night";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.034693, 0.025767, 0, -0};
    };
    class NVGoggles_INDEP: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\weapons_f\reticle\optics_night";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.034693, 0.025767, 0, -0};
    };
    class NVGoggles_OPFOR: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\weapons_f\reticle\optics_night";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.034693, 0.025767, 0, -0};
    };
};
