// Generated by tools/gen_nvg_compat.py from rhsusf_c_troops.pbo - re-run the tool, do not edit.
#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = "RONIM - NVG overlay compat (rhsusf_c_troops)";
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"azeroot_ronim_main", "rhsusf_c_troops"};
        skipWhenMissingDependencies = 1;
        author = "Root, Azer0";
        authors[] = {"Root", "Azer0"};
        url = "https://github.com/A3-Root/Azer0ot_RONIM";
        VERSION_CONFIG;
    };
};

// modelOptics blanked so the engine no longer draws the overlay; RONIM draws the same texture itself
class CfgWeapons {
    class NVGoggles;
    class rhsusf_ANPVS_14: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\rhsusf\addons\rhsusf_infantry\gear\nvg\ANPVS_14_opt";
        azeroot_ronim_maskTexture = "\rhsusf\addons\rhsusf_infantry\gear\nvg\data\pvs14_recticle.paa";
        azeroot_ronim_opticQuad[] = {0.336568, 0.336568, -0.000006, 0.00003};
    };
    class rhsusf_ANPVS_15: rhsusf_ANPVS_14 {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\weapons_f\reticle\optics_night";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.034693, 0.025767, 0, -0};
    };
    class rhsusf_ANVIS: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\weapons_f\reticle\optics_night";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.034693, 0.025767, 0, -0};
    };
    class rhsusf_anvis_nvg_bc_caps: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\weapons_f\reticle\optics_night";
        azeroot_ronim_maskTexture = "\a3\weapons_f\data\nightvisiontl.paa";
        azeroot_ronim_opticQuad[] = {0.034693, 0.025767, 0, -0};
    };
    class rhsusf_ihadss_scope: NVGoggles {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\rhsusf\addons\rhsusf_infantry\gear\nvg\ANPVS_14_opt";
        azeroot_ronim_maskTexture = "\rhsusf\addons\rhsusf_infantry\gear\nvg\data\pvs14_recticle.paa";
        azeroot_ronim_opticQuad[] = {0.336568, 0.336568, -0.000006, 0.00003};
    };
    class rhsusf_Rhino: rhsusf_ANPVS_14 {
        modelOptics = "";
        azeroot_ronim_modelOptics = "\A3\Weapons_F\empty";
    };
};
